name: CI on PR

on: pull_request

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Lint
        run: zig fmt --check --ast-check src/

      - name: Download & extract test images
        run: |
          # cf. https://github.com/agda/agda/issues/4691
          if [ "${{ runner.os }}" = "Windows" ]; then
            "C:/msys64/usr/bin/wget.exe" https://qoiformat.org/qoi_test_images.zip
          else
            wget https://qoiformat.org/qoi_test_images.zip
          fi
          mkdir -p tests/images && unzip qoi_test_images.zip && mv qoi_test_images/* tests/images && rm -rf qoi_test_images qoi_test_images.zip
        shell: bash

      - name: Test
        run: zig build test
