name: CI on PR

on: pull_request

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Lint
        run: zig fmt --check --ast-check src/

      - name: Download test images archive
        uses: suisei-cn/actions-download-file@v1.3.0
        id: dl-test-images
        with:
          url: https://qoiformat.org/qoi_test_images.zip
          target: "."

      - name: Download & extract test images
        run: |
          mkdir -p tests/images && unzip $TEST_IMGS_ZIP && mv qoi_test_images/* tests/images && rm -rf qoi_test_images $TEST_IMGS_ZIP
        shell: bash
        env:
          TEST_IMGS_ZIP: ${{ steps.dl-test-images.outputs.filename }}

      - name: Test
        run: zig build test
